var number = [45, 68, 78, 56, 89, 98];
// number.push(63);
// console.log(number); 
var friends = ['kamal', 'karim', 'rahim', 'rahman'];
// friends.push('ohin');
// console.log(friends.indexOf('rahim'));
// friends.pop('rarim');
// console.log(friends);
number.pop(78);
console.log(number);